export const idElements = {
  overlay: document.querySelector("#overlay"),
  mealName: document.querySelector("#meal-name"),
  mealImage: document.querySelector("#meal-image"),
  logoImage: document.querySelector("#logo-image"),
  searchIcon: document.querySelector("#search-icon"),
  profileIcon: document.querySelector("#profile-icon"),
  filterButton: document.querySelector("#filter-button"),
  logoutButton: document.querySelector("#logout-button"),
  profilePopup: document.querySelector("#profile-popup"),
  mealCategory: document.querySelector("#meal-category"),
  hamburgerMenu: document.querySelector("#hamburger-menu"),
  nextMealButton: document.querySelector("#next-meal-button"),
  totalMealsSpan: document.querySelector("#total-meals-span"),
  preferencesForm: document.querySelector("#preferences-form"),
  mealDescription: document.querySelector("#meal-description"),
  mealSearchInput: document.querySelector("#meal-search-input"),
  searchInputForm: document.querySelector("#search-input-form"),
  preferencesPopup: document.querySelector("#preferences-popup"),
  dropdownMenuList: document.querySelector("#dropdown-menu-list"),
  newPasswordInput: document.querySelector("#new-password-input"),
  totalMinutesSpan: document.querySelector("#total-minutes-span"),
  mealDetailsPopup: document.querySelector("#meal-details-popup"),
  mealDetailsImage: document.querySelector("#meal-details-image"),
  themeSwitchButton: document.querySelector("#theme-switch-button"),
  profilePopupEmail: document.querySelector("#profile-popup-email"),
  totalCaloriesSpan: document.querySelector("#total-calories-span"),
  totalPortionsSpan: document.querySelector("#total-portions-span"),
  deleteAccountForm: document.querySelector("#delete-account-form"),
  previousMealButton: document.querySelector("#previous-meal-button"),
  changePasswordForm: document.querySelector("#change-password-form"),
  categoriesContainer: document.querySelector("#categories-container"),
  changePasswordPopup: document.querySelector("#change-password-popup"),
  dropdownMenuOverlay: document.querySelector("#dropdown-menu-overlay"),
  dietaryFiltersContainer: document.querySelector("#filters-container"),
  saveEditGenderButton: document.querySelector("#save-edit-gender-button"),
  addToFavoritesButton: document.querySelector("#add-to-favorites-button"),
  clearSearchInputIcon: document.querySelector("#clear-search-input-icon"),
  sortAndOrderContainer: document.querySelector("#sort-and-order-container"),
  clearShoppingListIcon: document.querySelector("#clear-shopping-list-icon"),
  saveEditUsernameButton: document.querySelector("#save-edit-username-button"),
  cancelEditGenderButton: document.querySelector("#cancel-edit-gender-button"),
  loadingAnimationSpinner: document.querySelector("#loading-animation-spinner"),
  addToShoppingListButton: document.querySelector("#add-to-shopping-list-button"),
  cancelEditUsernameButton: document.querySelector("#cancel-edit-username-button"),
  mealDetailsPopupMealName: document.querySelector("#meal-details-popup-meal-name"),
  profilePopupUsernameInput: document.querySelector("#profile-popup-username-input"),
  shoppingListGridContainer: document.querySelector("#shopping-list-grid-container"),
  saveEditPhoneNumberButton: document.querySelector("#save-edit-phone-number-button"),
  profilePopupErrorContainer: document.querySelector("#profile-popup-error-container"),
  profilePopupMaleRadioInput: document.querySelector("#profile-popup-male-radio-input"),
  openMealDetailsPopupButton: document.querySelector("#open-meal-details-popup-button"),
  closePreferencesPopupButton: document.querySelector("#close-preferences-popup-button"),
  cancelEditPhoneNumberButton: document.querySelector("#cancel-edit-phone-number-button"),
  profilePopupSuccessContainer: document.querySelector("#profile-popup-success-container"),
  mealIngredientsListContainer: document.querySelector("#meal-ingredients-list-container"),
  profilePopupFemaleRadioInput: document.querySelector("#profile-popup-female-radio-input"),
  profilePopupPhoneNumberInput: document.querySelector("#profile-popup-phone-number-input"),
  openChangePasswordPopupButton: document.querySelector("#open-change-password-popup-button"),
  deleteAccountConfirmationPopup: document.querySelector("#delete-account-confirmation-popup"),
  closeChangePasswordPopupButton: document.querySelector("#close-change-password-popup-button"),
  profilePopupEditUsernameButton: document.querySelector("#profile-popup-edit-username-button"),
  changePasswordPopupErrorContainer: document.querySelector("#change-password-popup-error-container"),
  profilePopupEditPhoneNumberButton: document.querySelector("#profile-popup-edit-phone-number-button"),
  profilePopupEditGenderButtonContainer: document.querySelector("#profile-popup-edit-gender-button-container"),
  profilePopupEditUsernameButtonContainer: document.querySelector("#profile-popup-edit-username-button-container"),
  openDeleteAccountConfirmationPopupButton: document.querySelector("#open-delete-account-confirmation-popup-button"),
  closeDeleteAccountConfirmationPopupButton: document.querySelector("#close-delete-account-confirmation-popup-button"),
  profilePopupEditPhoneNumberButtonContainer: document.querySelector(
    "#profile-popup-edit-phone-number-button-container"
  ),
  deleteAccountConfirmationPopupErrorContainer: document.querySelector(
    "#delete-account-confirmation-popup-error-container"
  )
};

export const classElements = {
  pagePopups: document.querySelectorAll(".popup"),
  closePopupSvgs: document.querySelectorAll(".close-popup-svg"),
  showPasswordIcons: document.querySelectorAll(".toggle-password-icon"),
  ingredientsListContainers: document.querySelectorAll(".ingredients-list-container")
};
