export const idElements = {
  overlay: document.querySelector("#overlay"),
  logoImage: document.querySelector("#logo-image"),
  loginForm: document.querySelector("#login-form"),
  signupForm: document.querySelector("#signup-form"),
  loginPopup: document.querySelector("#login-popup"),
  loginInput: document.querySelector("#login-input"),
  signupPopup: document.querySelector("#signup-popup"),
  showLoginButton: document.querySelector("#show-login-button"),
  showSignupButton: document.querySelector("#show-signup-button"),
  signupEmailInput: document.querySelector("#signup-email-input"),
  themeSwitchButton: document.querySelector("#theme-switch-button"),
  loginSignupButton: document.querySelector("#login-signup-button"),
  loginPasswordInput: document.querySelector("#login-password-input"),
  resetPasswordButton: document.querySelector("#reset-password-button"),
  forgotPasswordPopup: document.querySelector("#forgot-password-popup"),
  loginErrorContainer: document.querySelector("#login-error-container"),
  signupPasswordInput: document.querySelector("#signup-password-input"),
  signupUsernameInput: document.querySelector("#signup-username-input"),
  signupErrorContainer: document.querySelector("#signup-error-container"),
  signupSuccessContainer: document.querySelector("#signup-success-container"),
  loadingAnimationSpinner: document.querySelector("#loading-animation-spinner"),
  signupConfirmPasswordInput: document.querySelector("#signup-confirm-password-input"),
};

export const classElements = {
  pagePopups: document.querySelectorAll(".popup"),
  closePopupSvgs: document.querySelectorAll(".close-popup-svg"),
  showPasswordIcons: document.querySelectorAll(".toggle-password-icon"),
};
