export const idElements = {
  overlay: document.querySelector("#overlay"),
  loginForm: document.querySelector("#login-form"),
  signupForm: document.querySelector("#signup-form"),
  loginPopup: document.querySelector("#login-popup"),
  loginInput: document.querySelector("#login-input"),
  signupPopup: document.querySelector("#signup-popup"),
  showLoginButton: document.querySelector("#show-login-button"),
  closeLoginSvg: document.querySelector("#close-login-popup-svg"),
  showSignupButton: document.querySelector("#show-signup-button"),
  signupEmailInput: document.querySelector("#signup-email-input"),
  themeSwitchButton: document.querySelector("#theme-switch-button"),
  loginSignupButton: document.querySelector("#login-signup-button"),
  closeSignupSvg: document.querySelector("#close-signup-popup-svg"),
  loginPasswordInput: document.querySelector("#login-password-input"),
  resetPasswordButton: document.querySelector("#reset-password-button"),
  forgotPasswordPopup: document.querySelector("#forgot-password-popup"),
  loginErrorContainer: document.querySelector("#login-error-container"),
  signupPasswordInput: document.querySelector("#signup-password-input"),
  signupUsernameInput: document.querySelector("#signup-username-input"),
  signupErrorContainer: document.querySelector("#signup-error-container"),
  signupSuccessContainer: document.querySelector("#signup-success-container"),
  loadingAnimationSpinner: document.querySelector("#loading-animation-spinner"),
  closeForgotPasswordSvg: document.querySelector("#close-forgot-password-popup-svg"),
  signupConfirmPasswordInput: document.querySelector("#signup-confirm-password-input"),
};

export const classElements = {
  showPasswordIcons: document.querySelectorAll(".toggle-password-icon"),
};