INSERT IGNORE INTO ingredients
VALUES
("Hot Dog", "Meats", "Can"),
("Round Beef Roast", "Meats", "Gram"),
("Proscuitto", "Meats", "Gram"),
("Beef Flank Steak", "Meats", "Gram"),
("Yellow Mustard", "Condiments", "Milliliter"),
("Barbecue Sauce", "Condiments", "Milliliter"),
("Brown Sugar", "Sweeteners", "Gram"),
("White Sugar", "Sweeteners", "Gram"),
("Granulated Sugar", "Sweeteners", "Gram"),
("Cayenne Pepper", "Spices", "Gram"),
("Onion Powder", "Spices", "Gram"),
("Ground Black Pepper", "Spices", "Gram"),
("Ground Ginger", "Spices", "Gram"),
("Sweet Paprika", "Spices", "Gram"),
("Onion Powder", "Spices", "Gram"),
("Garlic Powder", "Spices", "Gram"),
("Cayenne Pepper", "Spices", "Gram"),
("Kosher Salt", "Spices", "Gram"),
("Cubeb Pepper", "Spices", "Gram"),
("Red Pepper Flakes", "Spices", "Gram"),
("Water", "Beverages", "Milliliter"),
("Salted Butter", "Dairy", "Gram"),
("Parmigiano-Reggiano Cheese", "Dairy", "Gram"),
("Full-Fat Cream Cheese", "Dairy", "Gram"),
("Eggs", "Dairy", "Piece"),
("Yolks", "Dairy", "Piece"),
("Heavy Cream", "Dairy", "Milliliter"),
("Yolks", "Dairy", "Piece"),
("Cheddar Cheese", "Dairy", "Gram"),
("Unsalted Butter", "Dairy", "Gram"),
("Breadcrumbs", "Grains", "Gram"),
("White Flour", "Grains", "Gram"),
("Peanut Butter Powder", "Grains", "Gram"),
("Grains Of Selim", "Grains", "Gram"),
("Panko Breadcrumbs", "Grains", "Gram"),
("Minced Anchovy", "Seafood", "Gram"),
("Garlic Clove", "Vegetables", "Head"),
("Lemon Zest", "Vegetables", "Gram"),
("Broccoli", "Vegetables", "Gram"),
("Red Onions", "Vegetables", "Gram"),
("Coriander Leaves", "Vegetables", "Leaf"),
("Tomatoes", "Vegetables", "Gram"),
("Lime", "Vegetables", "Piece"),
("Crisp Lettuce", "Vegetables", "Gram"),
("Parsley Leaves", "Vegetables", "Leaf"),
("Yellow Onion", "Vegetables", "Gram"),
("Dry White Wine", "Beverages", "Milliliter"),
("Whole Peeled Tomatoes", "Vegetables", "Gram"),
("Olive Oil", "Fats", "Milliliter"),
("Peanut Oil", "Fats", "Milliliter"),
("Vanilla Extract", "Extracts", "Milliliter"),
("Pine Nuts", "Nuts", "Gram");